version: "3.8"
services:
  delta_broker:
    build:
      context: ..
      dockerfile: .docker/delta.dockerfile
    image: delta:latest
    restart: unless-stopped
    env_file:
      - ../.dev.env
    environment:
      - DELTA_SERVICE=broker
    networks:
      - delta_backbone
    ports:
      - "25555:25555"
      - "25556:25556"
    volumes:
      - ${DELTA_DB_PATH}:/deltadb
      - "/tmp:/tmp"

networks:
  delta_backbone:
    driver: bridge
    name: delta_backbone